name: Trigger Another Repo Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger second repo workflow
        run: |
          curl -X POST \
          -H "Authorization: token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/Jaimin180296/testng-browserstack/dispatches \
          -d '{"event_type": "trigger-second-repo-workflow"}'
